language: objective-c
osx_image: xcode11.3
cache:
  bundler: true
  cocoapods: true
  directories:
    - ~/.cocoapods
    - ~/Library/Caches/CocoaPods
    - .bundle
    - vendor
install:
  - set -o pipefail
  - sudo systemsetup -settimezone Asia/Ho_Chi_Minh
  - ./scripts/install
script:
  - ./scripts/lint
  - bundle exec fastlane tests
